DATAFRAME_DECIMALS:             8
FPS:                            50
BORDER_SPACE_FRAC:              0.1
SCREEN_WIDTH:                   1920
SCREEN_HEIGHT:                  1080
TEXT_START_FRAC:                0.02
ANIMATION_STARTUP_RUN_STATE:    0
ANIMATION_STARTUP_DEBUG_STATE:  1
COLOR_DEPTH:                    32
TIME_BAR_HEIGHT:                5
DEBUG_TEXT_SEP:                 14
WINDOW_NAME:                    "Spring Mesh"
INDICATORS_COLOR:               "#D3D3D3"
BACKGROUND_COLOR:               "#010001"
FONT:                           "Roboto-Bold"